# Generated by Django 4.1.3 on 2022-11-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0002_familiar2_familiar3_rename_familiar_familiar1'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar1',
            name='apodo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='familiar2',
            name='apodo',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='familiar3',
            name='apodo',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
